=== Kvalitetsdimensjonen «fullstendighet»[[fullstendighet]]

Kvalitetsdimensjonen https://data.norge.no/vocabulary/quality-dimension#completeness[fullstendighet] handler både om mangel på elementer i datasettet (kvalitetsdeldimensjon https://data.norge.no/vocabulary/quality-dimension#under-coverage[underdekning]) og overflødige elementer i datasettet (kvalitetsdeldimensjon https://data.norge.no/vocabulary/quality-dimension#over-coverage[overdekning]). Disse har kvalitetsmål på både enhets- og egenskapsnivå. Videre kan fullstendighet måles ut fra tre ulike verdityper, boolsk (ja/nei) på enhetsnivå, antall og andel på både enhets- og egenskapsnivå. Fritekst-feltet kan brukes til å opplyse om hvilken gitt egenskap som det mangler verdier for (for eksempel «bruksareal»).

[cols=100%]
|===
a| Eksempel: I vårt eksempeldatasett over byggninger mangler det 2 bygninger, og dette utgjør ca. 0,02%. 

Eksemplet uttrykt i RDF Turtle i henhold til DQV-AP-NO blir (eksemplet er ikke komplett slik at det kan mangle verdier for obligatoriske felter):

-----
:dsBuildings a dcat:Dataset ; # et datasett
   dqv:hasQualityMeasurement # har måleresultat
      :qmMissingObjects , # manglende enheter
      :qmNumberMissingObjects , # antall manglende enheter
      :qmRateMissingObjects . # andel manglende enheter

:qmMissingObjects a dqv:QualityMeasurement ; # et måleresultat
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-completeness-1001> ; # manglende enheter
   dqv:value "true"^^xsd:boolean ;
   rdfs:comment "Ja, noen bygninger mangler i datasettet."@nb ,
      "Yes, some buildings are missing in the dataset."@en .

:qmNumberMissingObjects a dqv:QualityMeasurement ; # et måleresultat
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-completeness-1002> ; # antall manglende enheter
   dqv:value "2"^^xsd:nonNegativeInteger ;
   rdfs:comment "To bygninger mangler i datasettet."@nb ,
      "Two buildings are missing in the dataset."@en .

:qmRateMissingObjects a dqv:QualityMeasurement ; # et måleresultat
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-completeness-1003> ; # andel manglende enheter
   dqv:value "0.02"^^xsd:double ;
   rdfs:comment "0,02% av bygninger mangler i datasettet."@nb ,
               "0.02% of buildings are missing in the dataset."@en .
-----
|===

Fullstendighet handler også om https://data.norge.no/vocabulary/quality-dimension#imputation[imputering]. Imputering er å fylle inn verdi for en gitt egenskap der verdien mangler eller er ubrukbar. Dette gjøres for å håndtere manglende verdier for egenskaper (tomme celler) i et datasett der disse manglende verdiene skaper problemer for, blant annet, analysen av dataene. Imputerte verdier som kvalitetsmål gir datatilbyderen mulighet til å informere brukerne av datasettet at det er egenskaper i datasettet som ikke er hentet fra virkeligheten. 

[cols=100%]
|===
a| Eksempel: Egenskapen «byggeår» for fire av de eldre bygningene i eksempeldatasettet vårt har fått impurterte verdier. 

Eksemplet uttrykt i RDF Turtle i henhold til DQV-AP-NO blir (eksemplet er ikke komplett slik at det kan mangle verdier for obligatoriske felter):

-----
:dsBuildings a dcat:Dataset ; # et datasett
   dqv:hasQualityMeasurement # har måleresultat
      :qmNumberImputedValues . # antall impurterte verdier
   
:qmNumberImputedValues a dqv:QualityMeasurement ; # et måleresultat
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-completeness-3001> ; # andel enheter med imputert verdi for en gitt egenskap
   dqv:value "4"^^xsd:nonNegativeInteger ;
   rdfs:comment "Fire bygninger har fått imputert verdi for egenskapen 'byggeår'."@nb ,
      "Four buildings have got imputed value for the property 'year of construction'."@en .
-----
|===

=== Kvalitetsdimensjonen «aktualitet»

Det er predefinert ett kvalitetsmål i kvalitetsdimensjonen https://data.norge.no/vocabulary/quality-dimension#currentness[aktualitet] – https://data.norge.no/vocabulary/quality-metric#qm-currentness-1001[samlet tidsdifferanse].

[cols=100%]
|===
a| Eksempel: For bygninger i eksempeldatasettet vårt tar det statistisk sett ca. 24 dager fra en bygning kontraktsmessig skifter eier til eierskiftet blir meldt inn. Medregnet intern saksbehandlingstid setter datatilbydren «30 dager» som «samlet tidsdifferanse».

Eksemplet uttrykt i RDF Turtle i henhold til DQV-AP-NO blir (eksemplet er ikke komplett slik at det kan mangle verdier for obligatoriske felter):

-----
:dsBuildings a dcat:Dataset ; # et datasett
   dqv:hasQualityMeasurement # har måleresultat
      :qmOverallDelay . # samle tidsdifferanse

:qmOverallDelay a dqv:QualityMeasurement ; # et måleresultat 
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-currentness-1001> ; # samlet tidsdifferanse
   dqv:value "P30D"^^xsd:duration ;
   rdfs:comment "Det tar i gjennomsnitt 24 dager fra en bygning står ferdig eller er revet til den er innlemmet i eller tatt ut fra datasettet. Medregnet intern saksbehandlingstid blir den samlede tidsdifferansen 30 dager."@nb ,
      "On average there will be 24 days from a building is completed or demolished, to it is included in or excluded from the dataset. With internal processing time included, the overall time difference is 30 days."@en .
-----
|===


=== Kvalitetsdimensjonen «konsistens»

Kvalitetsdimensjonen https://data.norge.no/vocabulary/quality-dimension#consistency[konsistens] gjelder konsistens innad i ett og samme datasett, og ikke konsistens mellom datasett. Om datasettet er i samsvar med gitte standarder og krav er ikke definert på nytt som et eget kvalitetsmål ettersom dette er dekket av DCAT-AP-NO https://data.norge.no/specification/dcat-ap-no/#datasett-i-samsvar-med[(Datasett: i samsvar med)]. Et eksempel på slik innbyrdes inkonsistens er når bruksareal er større enn bruttoareal for en bygning.

Kvalitetsdimensjonen konsistens kan i mange tilfeller lett forveksles med kvalitetsdimensjonen nøyaktighet. Det som bl.a. skiller nøyaktighet og konsistens er at når det gjelder konsistens _vet man ut fra vurdering av flere egenskaper at det er feil, men ikke hvilken eller hvilke egenskaper som er feil_ i datasettet. I eksemplet over er det ikke mulig å avgjøre om det er bruksareal eller bruttoareal (eller begge) som er feil. Når det gjelder nøyaktighet, _vet man hvilken egenskap som er feil_ (for eksempel feil identifikator).

Det første kvalitetsmålet i konsistens (https://data.norge.no/vocabulary/quality-metric#qm-consistency-1001[andel enheter med inkonsistente egenskaper]) måles på enhetsnivå. Her måles andel enheter som har en form for inkonsistens knyttet til seg. Det andre kvalitetsmålet (https://data.norge.no/vocabulary/quality-metric#qm-consistency-1002[andel enheter med inkonsistens mellom gitte egenskaper]) går mer i dybden og brukes der man har innsikt i hva inkonsistensen gjelder på egenskapsnivå. Kvalitetsmålene oppgis i prosentandel; fritekstfeltet kan brukes til å forklare for hvilke egenskaper inkonsistensen gjelder.

[cols=100%]
|===
a| Eksempel: For vårt eksempeldatasett er det ca. 0,03% av bygningene som har inkonsistens mellom egenskapene "bruksareal" og "bruttoareal". 

Eksemplet uttrykt i RDF Turtle i henhold til DQV-AP-NO blir (eksemplet er ikke komplett slik at det kan mangle verdier for obligatoriske felter):

-----
:dsBuildings a dcat:Dataset ; # et datasett
   dqv:hasQualityMeasurement # har måleresultat
      :qmRateInconsistencyGivenProperties . # andel enheter med inkonsistens mellom gitte egenskaper

:qmRateInconsistencyGivenProperties a dqv:QualityMeasurement ; # et måleresultat 
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-consistency-1002> ; # andel enheter med inkonsistens mellom gitte egenskaper
   dqv:value "0.03"^^xsd:double ;
   rdfs:comment "0,03% av bygningene i datasettet står oppført med 'bruksareal' som er høyere enn 'bruttoareal'."@nb ,
      "0.03% of the buildings in the dataset have 'usable area' larger than 'gross area'."@en .
-----
|===

=== Kvalitetsdimensjonen «nøyaktighet»

I kvalitetsdimensjonen https://data.norge.no/vocabulary/quality-dimension#accuracy[nøyaktighet] måles i hvilken grad dataene korrekt representerer virkeligheten.

Nøyaktighet av en dataverdi er ofte avhengig av type data, og kvalitetsmål for nøyaktighet blir fort svært fag- og sektorspesifikke. De mest generelle nøyaktighetsmålene er derfor plukket ut i denne sammenheng: https://data.norge.no/vocabulary/quality-dimension#identifier-correctness[identifikatorriktighet] som går på identifikasjonsnøkler, og https://data.norge.no/vocabulary/quality-dimension#classification-correctness[klassifikasjonsriktighet] som går på bruk av klassifikasjoner og kodeverk.

[cols=100%]
|===
a| Eksempel: For vårt eksempeldatasett er det ca. 0,01% av bygningene som har fått feil identifikator. 

Eksemplet uttrykt i RDF Turtle i henhold til DQV-AP-NO blir (eksemplet er ikke komplett slik at det kan mangle verdier for obligatoriske felter):

-----
:dsBuildings a dcat:Dataset ; # et datasett
   dqv:hasQualityMeasurement # har måleresultat
      :qmRateIncorrectIdentifier . # andel enheter med identifikatorfeil

:qmRateIncorrectIdentifier a dqv:QualityMeasurement ; # et måleresultat 
   dqv:isMeasurementOf <https://data.norge.no/vocabulary/quality-metric#qm-accuracy-1002> ; # andel enheter med inkonsistens mellom gitte egenskaper
   dqv:value "0.01"^^xsd:double ;
   rdfs:comment "0,01% av bygningene i datasettet har fått feil identifikator."@nb ,
      "0.01% of the buildings in the dataset have wrong identifiers."@en .
-----
|===
