name: Build adocs and publish develop to GitHub pages

permissions:
  contents: write
  pages: write

on:
  push:
    branches:
      - develop
    paths:
      - "docs/**"
  workflow_dispatch:

jobs:
  adoc_build:
    name: asciidoctor build
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-github-pages.yaml@main
    with:
      program_html: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"
      program_pdf: "asciidoctor-pdf -D docs -o files/veileder-kvantifiserbar-kvalitet.pdf -a lang=nb docs/main.adoc"
      publish_branch: gh-pages
      publish_dir: ./docs
    secrets:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
