name: Build adocs and publish v1 to production

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    runs-on: ubuntu-latest
    name: asciidoctor build

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: v1

      - name: Build html
        id: adocbuild_html
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"

      - name: Build pdf
        id: adocbuild_pdf
        uses: tonynv/asciidoctor-action@master
        with:
          program: "asciidoctor-pdf -D docs -o files/veileder-kvantifiserbar-kvalitet.pdf -a lang=nb docs/main.adoc"
        continue-on-error: true

      - name: Upload files to static-rdf-server
        uses: Informasjonsforvaltning/upload-files-to-static-rdf-server-action@v3.2.0
        id: upload-files
        with:
          ontology-type: "guide"
          ontology: "veileder-kvantifiserbar-kvalitet"
          host: "https://data.norge.no"
          api-key: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
          files: |
            docs/index.html text/html nb
            docs/files/veileder-kvantifiserbar-kvalitet.pdf application/pdf nb files/veileder-kvantifiserbar-kvalitet.pdf
            docs/images/Digdir.png image/png nb images/Digdir.png
            docs/images/eksempeldatasett.png image/png nb images/eksempeldatasett.png
            docs/images/sammenheng.png image/png nb images/sammenheng.png
