name: Build adocs and publish v1 to production

permissions:
  contents: read

on:
  push:
    branches:
      - v1
    paths:
      - docs/**
  workflow_dispatch:

jobs:
  adoc_build:
    name: asciidoctor build
    uses: Informasjonsforvaltning/workflows/.github/workflows/specification-upload-files.yaml@main
    with:
      ref: v1
      program_html: "asciidoctor -D docs -o index.html -a lang=nb docs/main.adoc"
      program_pdf: "asciidoctor-pdf -D docs -o files/veileder-kvantifiserbar-kvalitet.pdf -a lang=nb docs/main.adoc"
      files: |
        docs/index.html text/html nb
        docs/files/veileder-kvantifiserbar-kvalitet.pdf application/pdf nb files/veileder-kvantifiserbar-kvalitet.pdf
        docs/images/Digdir.png image/png nb images/Digdir.png
        docs/images/eksempeldatasett.png image/png nb images/eksempeldatasett.png
        docs/images/sammenheng.png image/png nb images/sammenheng.png
      ontology-type: "guide"
      ontology: "veileder-kvantifiserbar-kvalitet"
      host: "https://data.norge.no"
    secrets:
      STATIC_RDF_SERVER_API_KEY: ${{ secrets.STATIC_RDF_SERVER_API_KEY }}
